include: all_lint_rules.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "lib/generated_plugin_registrant.dart"
  errors:
    included_file_warning: ignore

linter:
  rules:
    prefer_double_quotes: false
    always_put_control_body_on_new_line: false
    public_member_api_docs: false
    prefer_final_parameters: false
    sort_pub_dependencies: false
    prefer_expression_function_bodies: false
    always_specify_types: false
    unnecessary_final: false
    always_use_package_imports: false
    prefer_int_literals: false
    sort_constructors_first: false
    always_put_required_named_parameters_first: false
    diagnostic_describe_all_properties: false
    lines_longer_than_80_chars: false
    require_trailing_commas: false
    library_private_types_in_public_api: false
